GET http://localhost:8080/api/reservations/list

###

POST http://localhost:8080/api/reservations/
Content-Type: application/json

{
  "roomId": 1,
  "personId": 1,
  "startTime": "2023-12-02T11:50:00",
  "endTime": "2023-12-02T15:50:00",
  "reservationDate": "2023-12-02"
}

###

GET http://localhost:8080/api/reservations/1

###

PUT http://localhost:8080/api/reservations/1
Content-Type: application/json

{
  "roomId": 1,
  "personId": 1,
  "startTime": "2023-12-02T11:50:00",
  "endTime": "2023-12-02T11:50:00",
  "reservationDate": "2023-12-02"
}

###

DELETE http://localhost:8080/api/reservations/1
Content-Type: application/json

###
//test

POST http://localhost:8080/api/reservations/
Content-Type: application/json

{
  "roomId": 1,
  "personId": 1,
  "startTime": "2023-12-14T08:00:00",
  "endTime": "2023-12-14T08:50:00",
  "reservationDate": "2023-12-14"
}

###

DELETE http://localhost:8080/api/reservations/1
Content-Type: application/json

### Persons ###

### Get Person

GET http://localhost:8080/api/persons/list

###