@startuml

entity Room {
- id
- name
- description
}

entity Reservation {
- id
- roomId
- personId
- date
- startTime
- endTime
}


entity Person {
- id
- surname
- firstname
}



Room "1"--"*" Reservation
Person "1"--"*" Reservation

@enduml