@startuml

abstract Reservable {
- id
- name
- description
}

entity Inventory {
- id
- typeId
- name
- itemCount
- available
}

entity Equipment {
- type
- labelNr
}

entity Room {
- roomLocation
}

entity Reservation {
- id
- roomId
- personId
- date
- startTime
- endTime
}


entity Person {
- id
- surname
- firstname
}


Reservable <|-- Equipment
Reservable <|-- Room
Room "1"--"*" Reservation
Person "1"--"*" Reservation
Inventory "1" -- "*" Equipment

@enduml