= Projekt ITP
1.0.0, {docdate}: ITP
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:experimental:


== Projektauftrag

=== Projektname
OmniaL

=== Ausgangssituation
In der Htl-Leonding ist eine mittelgroße Schule in Oberösterreich.
Viele Schüler arbeiten in der Schule an diversen Projekten/Aufgaben. +
Oftmals fällt es schwer einen Raum zu finden welcher frei ist, da Reservierungen für z.B. EDV-Sääle sind an der Schule nur für Lehrer möglich sind. +
Die Entlehnung von Equipment wird auf einem Blatt Papier ausgeführt, wodurch beim Ausleihen Fehler unterlaufen können. +
Auch haben Schüler keine Informationen wann das jeweilige Equipment wieder verfügbar ist. +

=== Projektbeschreibung
Eine Anwendung die es Schülern und Lehrern ermöglicht Räume zu reservieren sowie die Entlehnung von Equipment durchzuführen. +
Die Raumreservierung wird ähnlich zu WebUntis wie ein Kalender gestaltet sein, woduch Schüler bei leeren Räumen eine Reservierung machen können. +
Falls Lehrer einen Raum für Unterrichtungszwecke benötigen, haben diese allerdings Vorrang. +
Zwecks Entlehnung gibt es eine Veranschaulichung des gesammten Equipments und ob dieses gerade Verfügbar ist. +
Sollte dieses gerade ausgeliehen sein, so gibt es auch ein Datum bis wann die Entlehnung erfolgt.
Eine Verlängerun der Entlehnung kann per Antrag an den Lehrer geschickt werden.

=== Projektziel / Nicht-Ziele
* Schüler wird das planen der Projekte erleichtert
* Die Entlehnung des Equipments ist übersichtlicher und Lehrern wird das Management der Geräte erleichtert.

=== Projektinhalte
* Die Schüler können über ein Kalendersystem einen Raum reservieren.
* Lehrer können diese Reservierung überschreiben sofern sie diesen für Unterricht benötigen.
* Ein Raum kann immer nur einmal reserviert werden und das nur auf eine gewisse Zeitspanne.
* Die Entlehnung erfolgt über eine Digitale Liste, welch auch ausgedruckt werden kann.

=== Kritische Erfolgsfaktoren
* *Zeitrahmen*: Das Projekt muss bis zum Projectaward 2025 abgeschlossen sein.
* *Qualität*: Die Benutzeroberfläche soll anfängerfreundlich und übersichtlich sein.
* *Resourcen*: Die benötigten Ressourcen (z.B. Schülerlogins) müssen verfügbar sein.

=== Termine
==== Projektstart
Dienstag 10.10.2023

==== Projektende
Projectaward 2025

====  Meilensteine
* Ausdruckbare Entlehnungsliste
* Funktionierendes Kalendersystem
* Anmeldung per Schülerdaten
* Raumreservierung
* Entlehung per digitaler Liste

=== Ressourcen / Kosten
Als Ressourcen werden die SChülerlogins beenötigt, zur überprüfung der Anmeldedaten.

=== Projektorganisation
==== Projektauftraggeber
Aberger Christian

==== Projektleiter
Sophie Stöger

==== Projektteammitglieder
- Sophie Stöger
- Sophie Binder
- Moritz Wagner
- Maximillian Slabschi




----
Unterschrift Auftraggeber:___________________

Unterschrift Projektleiter:___________________
----

